# Generated by Django 3.1.4 on 2020-12-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('pending_delivery', 'PENDING_DELIVERY'), ('delivered', 'DELIVERED'), ('cancelled', 'CANCELLED')], default='pending_delivery', max_length=20)),
                ('receiver', models.ForeignKey(limit_choices_to={'group_names': 'customers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
